name: Deploy to GCP VM

on:
  push:
    branches: [ main, stage ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/gcp-key
        chmod 600 ~/.ssh/gcp-key
        ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts
        
    - name: Deploy to Production VM (main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to Production VM..."
        ssh -i ~/.ssh/gcp-key admin@${{ secrets.GCP_VM_IP }} << 'EOF'
          echo "=== Production Deployment Started ==="
          cd /home/admin
          
          # Create deployment directory if it doesn't exist
          mkdir -p deployment
          cd deployment
          
          # Clone or update repository
          if [ -d "test-deployment" ]; then
            cd test-deployment
            git pull origin main
          else
            git clone https://github.com/mmparmar553/test-deployment.git
            cd test-deployment
          fi
          
          # Make script executable and run it
          chmod +x system-check.sh
          ./system-check.sh
          
          echo "=== Production Deployment Complete ==="
        EOF
        
    - name: Deploy to Staging VM (stage branch)
      if: github.ref == 'refs/heads/stage'
      run: |
        echo "Deploying to Staging VM..."
        # For now, using same VM but different directory
        ssh -i ~/.ssh/gcp-key admin@${{ secrets.GCP_VM_IP }} << 'EOF'
          echo "=== Staging Deployment Started ==="
          cd /home/admin
          
          # Create staging deployment directory
          mkdir -p staging-deployment
          cd staging-deployment
          
          # Clone or update repository
          if [ -d "test-deployment" ]; then
            cd test-deployment
            git pull origin stage
          else
            git clone https://github.com/mmparmar553/test-deployment.git
            cd test-deployment
            git checkout stage
          fi
          
          # Make script executable and run it
          chmod +x system-check.sh
          ./system-check.sh
          
          echo "=== Staging Deployment Complete ==="
        EOF
